
# This is a basic workflow to help you get started with Actions
name: Deploy pull-request draft to S3 static site with PR branch name

on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    types: [ "close" ]

env:
  #These two values determine how bucket will be named
  BUCKET_NAME_STEM: sphinxtutorials3test
  PR_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Authenticate with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      #Delete bucket
      - name:  Delete bucket
        shell: bash -l {0}
        run: |
          #Define the bucket name
          BUCKET=$BUCKET_NAME_STEM-$PR_BRANCH_NAME
          #All files/objects must be deleted before bucket will delete
          aws s3 rm s3://$BUCKET --recursive
          aws s3 delete-bucket --bucket $BUCKET
    
